#!/bin/bash

#v0.5.9 Com Interface

#Se a sua função tiver apenas 1 escolha,
#Faça seu codigo dentro de funcaoX() { Seu código }.
#O conteúdo dentro dela pode ser deletado.

#Caso sua função possua mais de 1 escolha. Ex: Descompactar e Compactar,
#Utilize as areas escolhaX_fX() { Seu código }.
#Renomeie os botões com suas respectivas funções ( Acrescentar mais caso necessário ).

main(){

   funcao1(){
      escolha1_f1(){  
         caixa1(){
         clear
            echo "###############################################################"
            echo "#                                                             #"
            echo "#   Digite onde está localizado o arquivo (Ex: /home/usuario) #"
            echo "#                                                             #"
            echo "#                                                             #"
            echo "#   Digite o nome do arquivo                                  #"
            echo "#                                                             #"
            echo "#                                                             #"
            echo "###############################################################" 
         }
         comp_tar(){
            caixa1          
           
            tput cup 3 4
            read endereco
 
            tput cup 6 4
            read arqnome
 
            cd $endereco 2> log_tde

            tar -cf $arqnome.tar $arqnome 2> log_tde

            if [ $? -eq 0 ]; then
               tput cup 7 0
               echo "#                     *Arquivo compactado*"
               read -n 1 ; funcao1
            else
               tput cup 7 0
               echo "#               *Erro! Arquivo não foi compactado*"
               rm $arqnome.tar 2> log_tde
               read -n 1; funcao1
            fi
         }

         comp_gz(){
            caixa1          
           
            tput cup 3 4
            read endereco

            tput cup 6 4
            read arqnome

            cd $endereco 2> log_tde
            tar -czf $arqnome.tar.gz $arqnome 2> /dev/null
            if [ $? -eq 0 ]; then
               echo "#                     *Arquivo compactado*"
               read -n 1; funcao1
            else
               echo "#               *Erro! Arquivo não foi compactado*"
               rm $arqnome.tar.gz 2> log_tde
               read -n 1; funcao1
            fi
         }

         comp_bz2(){
            caixa1          
           
            tput cup 3 4
            read endereco
 
            tput cup 6 4
            read arqnome
 
            cd $endereco 2> log_tde

            tar -cjf $arqnome.tar.bz2 $arqnome 2> log_tde

            if [ $? -eq 0 ]; then
               tput cup 7 0
               echo "#                     *Arquivo compactado*"
               read -n 1 ; funcao1
            else
               tput cup 7 0
               echo "#               *Erro! Arquivo não foi compactado*"
               rm $arqnome.tar 2> log_tde
               read -n 1; funcao1
            fi
         }

            clear
            echo "#######################################################################"
            echo "#                                                                     #"
            echo "#                        Compactação de Arquivos                      #"
            echo "#                                                                     #"
            echo "#---------------------------------------------------------------------#"
            echo "#                                                                     #"
            echo "#   1) Compactar com .tar                                             #"
            echo "#   2) Compactar e Comprimir com .tar.gz                              #"
            echo "#   3) Compactar e Comprimir com .tar.bz2                             #"
            echo "#   4) Voltar                                                         #"
            echo "#                                                                     #"
            echo "#   Escolha uma Opção:                                               #"
            echo "#                                                                     #"
            echo "#######################################################################"
       
            tput cup 11 23
            read -n 10 escolha

            case $escolha in
            1) comp_tar;;
            2) comp_gz;;
            3) comp_bz2;;
            4) funcao1;;
            *) tput cup 12 0; echo "#                        *Comando Inválido*"; read -n 1; escolha1_f1;;
            esac
         }

      escolha2_f1(){
         caixa2(){
            clear
            echo "###############################################################"
            echo "#                                                             #"
            echo "#   Digite onde está localizado o arquivo (Ex: /home/usuario) #"
            echo "#                                                             #"
            echo "#                                                             #"
            echo "#   Digite o nome do arquivo (Ex: arquivo.tar/tar.gz/tar.bz2) #"
            echo "#                                                             #"
            echo "#                                                             #"
            echo "###############################################################"
         }
         desc_tar(){
            caixa2

            tput cup 3 4
            read endereco
            
            tput cup 6 4
            read arqnome

            cd $endereco 2> log_tde
               
            tar -xf $arqnome 2> log_tde

            if [ $? -eq 0 ]; then
               tput cup 7 0
               echo "#                     *Arquivo descompactado*"
               read -n 1; funcao1
            else
               tput cup 7 0
              read -n 1; funcao1
            fi
         }

         desc_gz(){
            caixa2

            tput cup 3 4
            read endereco
            
            tput cup 6 4
            read arqnome

            cd $endereco 2> log_tde
               
            tar -xzf $arqnome 2> log_tde

            if [ $? -eq 0 ]; then
               tput cup 7 0
               echo "#                     *Arquivo descompactado*"
               read -n 1; funcao1
            else
               tput cup 7 0
               read -n 1; funcao1
            fi
         }

         desc_bz2(){
            caixa2

            tput cup 3 4
            read endereco
            
            tput cup 6 4
            read arqnome

            cd $endereco 2> log_tde
               
            tar -xjf $arqnome 2> log_tde

            if [ $? -eq 0 ]; then
               tput cup 7 0
               echo "#                     *Arquivo descompactado*"
               read -n 1; funcao1
            else
               tput cup 7 0
               read -n 1; funcao1
            fi
         }

      clear
      echo "#######################################################################"
      echo "#                                                                     #"
      echo "#                       Descompactação de Arquivos                    #"
      echo "#                                                                     #"
      echo "#---------------------------------------------------------------------#"
      echo "#                                                                     #"
      echo "#   1) Descompactar arquivos .tar                                     #"
      echo "#   2) Descompactar e Descomprimir arquivos .tar.gz                   #"
      echo "#   3) Descompactar e Descomprimir arquivos .tar.bz2                  #"
      echo "#   4) Voltar                                                         #"
      echo "#                                                                     #"
      echo "#   Escolha uma Opção:                                                #"
      echo "#                                                                     #"
      echo "#######################################################################"
       
      tput cup 11 23
      read -n 10 escolha

      case $escolha in
      1) desc_tar;;
      2) desc_gz;;
      3) desc_bz2;;
      4) funcao1;;
      *) tput cup 12 0; echo "#                        *Comando Inválido*"; read -n 1; escolha2_f1;;
      esac
      }

      clear
      echo "#######################################################################"
      echo "#                                                                     #"
      echo "#                Compactação/Descompactação de Arquivos               #"
      echo "#                                                                     #"
      echo "#---------------------------------------------------------------------#"
      echo "#                                                                     #"
      echo "#   1) Compactar Arquivo                                              #"
      echo "#   2) Descompactar Arquivo                                           #"
      echo "#   3) Voltar                                                         #"
      echo "#                                                                     #"
      echo "#   Escolha uma Opção:                                                #"
      echo "#                                                                     #"
      echo "#######################################################################"

      tput cup 10 23

      read -n 10 escolha

      case $escolha in
      1)escolha1_f1;;
      2)escolha2_f1;;
      3)main;;
      *)tput cup 11 0; echo "#                         *Comando Inválido*"; read -n 1; funcao1;;
      esac
   }

   funcao2(){
      escolha1_f2(){
         clear
         echo "Função em Criação es1 f2"; read; funcao2;
      }
      escolha2_f2(){
         clear
         echo "Função em Criação es2 f2"; read; funcao2;
      }
      clear
      echo "#######################################################################"
      echo "#                                                                     #"
      echo "#                    Você está na tela da Função 2                    #"
      echo "#                                                                     #"
      echo "#---------------------------------------------------------------------#"
      echo "#                                                                     #"
      echo "#   1) Primeira Escolha                                               #"
      echo "#   2) Segunda Escolha                                                #"
      echo "#   3) Voltar                                                         #"
      echo "#                                                                     #"
      echo "#   Escolha uma Opção:                                                #"
      echo "#                                                                     #"
      echo "#######################################################################"

      tput cup 10 23

      read -n 10 escolha

      case $escolha in
      1)escolha1_f2;;
      2)escolha2_f2;;
      3)main;;
      *)tput cup 11 0; echo "#                         *Comando Inválido*"; read -n 1; funcao2;;
      esac
   }

   funcao3(){
      escolha1_f3(){
         clear
         echo "Função em Criação es1 f3"; read; funcao3;
      }
      escolha2_f3(){
         clear
         echo "Função em Criação es2 f3"; read; funcao3;
      }
      clear
      echo "#######################################################################"
      echo "#                                                                     #"
      echo "#                    Você está na tela da Função 3                    #"
      echo "#                                                                     #"
      echo "#---------------------------------------------------------------------#"
      echo "#                                                                     #"
      echo "#   1) Primeira Escolha                                               #"
      echo "#   2) Segunda Escolha                                                #"
      echo "#   3) Voltar                                                         #"
      echo "#                                                                     #"
      echo "#   Escolha uma Opção:                                                #"
      echo "#                                                                     #"
      echo "#######################################################################"

      tput cup 10 23

      read -n 10 escolha

      case $escolha in
      1)escolha1_f3;;
      2)escolha2_f3;;
      3)main;;
      *)tput cup 11 0; echo "#                         *Comando Inválido*"; read -n 1; funcao3;;
      esac
   }

   funcao4(){
      escolha1_f4(){
         clear
         echo "Função em Criação es1 f4"; read; funcao4;
      }
      escolha2_f4(){
         clear
         echo "Função em Criação es2 f4"; read; funcao4;
      }
      clear
      echo "#######################################################################"
      echo "#                                                                     #"
      echo "#                    Você está na tela da Função 4                    #"
      echo "#                                                                     #"
      echo "#---------------------------------------------------------------------#"
      echo "#                                                                     #"
      echo "#   1) Primeira Escolha                                               #"
      echo "#   2) Segunda Escolha                                                #"
      echo "#   3) Voltar                                                         #"
      echo "#                                                                     #"
      echo "#   Escolha uma Opção:                                                #"
      echo "#                                                                     #"
      echo "#######################################################################"

      tput cup 10 23

      read -n 10 escolha

      case $escolha in
      1)escolha1_f4;;
      2)escolha2_f4;;
      3)main;;
      *)tput cup 11 0; echo "#                         *Comando Inválido*"; read -n 1; funcao4;;
      esac
   }

   clear
   echo "#######################################################################"
   echo "#                                                                     #"
   echo "# UNIGRANRIO - Universidade do Grande Rio                             #"
   echo "# Sistemas Operacionais Abertos                    Semestre 2 de 2015 #"
   echo "#---------------------------------------------------------------------#"
   echo "# Professor: Luiz Fernando T. de Farias            Turma:  EIN 359-02 #"
   echo "# Equipe desenvolvedora:                                              #"
   echo "#          Aluno: Marcos Geovane Guimarães Filho                      #"
   echo "#          Aluno:                                                     #"
   echo "#          Aluno:                                                     #"
   echo "#          Aluno:                                                     #"
   echo "#---------------------------------------------------------------------#"
   echo "# Rio de Janeiro,  `date +%d` de `date +%B` de `date +%Y`                              #"
   echo "# Hora do Sistema: `date +%H` Horas e `date +%M` Minutos                              #"
   echo "#---------------------------------------------------------------------#"
   echo "# Menu de Escolhas:                                                   #"
   echo "#        1) Compactação/Descompactação de Arquivos                    #"
   echo "#        2) Função 2                                                  #"
   echo "#        3) Função 3                                                  #"
   echo "#        4) Função 4                                                  #"
   echo "#        5) Finalizar o script                                        #"
   echo "#                                                                     #"
   echo "#        Escolha uma opção:                                           #"
   echo "#                                                                     #"  
   echo "#######################################################################"

#tput cup posiociona o ponteiro(area da digitação) na posição de X,Y 
#X= Linha | Y= Coluna
   tput cup 21 28

#-n<Numero> ele irá ler opção e aceitar até no maximo 10 caracteres
   read -n 10 opcao

#Quando o usuario finalizar o script ele irá limpar a tela
   trap "clear" EXIT
   
   case $opcao in
   1) funcao1;;
   2) funcao2;;
   3) funcao3;;
   4) funcao4;;
   5) exit;;
   *) tput cup 22 0; echo "#                         *Comando Inválido*"; read -n 1; main;;
   esac
}
main

